name: mvfoul
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - einops
  - imageio
  - matplotlib
  - moviepy=1.0.3
  - pandas
  - pyqt
  - numpy
  - pillow
  - scipy
  - tqdm
  - opencv
  - scikit-learn
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - --extra-index-url https://pypi.nvidia.com
    - torch
    - torchvision
    - torchaudio
    - soccernet
    - av
    - pyav
    - pydub
    - audiofile
    - mmcv
    - git+https://github.com/facebookresearch/xformers@v0.0.18
    - git+https://github.com/ajhamdi/mvtorch 
    - git+https://github.com/facebookresearch/dinov2

  