
services:
  depth-estimation:
    image: edouarddem/dino-v2-depth
    container_name: depth-estimation
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DEPTHER_BACKBONE_SIZE=large
      - DEPTHER_HEAD_TYPE=dpt
      - DEPTHER_HEAD_DATASET=nyu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 
              
  segmentation:
    image: edouarddem/dino-v2-segmentation
    container_name: segmentation
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - SEGMENTOR_BACKBONE_SIZE=large
      - SEGMENTOR_HEAD_TYPE=ms
      - SEGMENTOR_HEAD_DATASET=voc2012
      - SEGMENTOR_HEAD_SCALE_COUNT=3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 